[build]
  publish = 'public/'
  functions = 'functions'
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
